//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAntony
{
    using System;
    using System.Collections.Generic;
    
    public partial class Major
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Department_Id { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
