//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        public int Id { get; set; }
        public int Person_ID { get; set; }
        public int Semester { get; set; }
        public int Course_ID { get; set; }
        public int Section_ID { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Person Person { get; set; }
        public virtual Section Section { get; set; }
        public virtual Semester Semester1 { get; set; }
    }
}
